spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8080
          predicates:
            - Path=/v1/auth/**
        - id: users-route
          uri: http://localhost:8081
          predicates:
            - Path=/v1/user/**
          filters:
            - name: AuthenticationFilter
        - id: notifications-route
          uri: http://localhost:8082
          predicates:
            - Path=/v1/notifications/**
          filters:
            - name: AuthenticationFilter

  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

server:
  port: 8083
